export const COMMON_TECH = [
    { name: 'React', image: '/images/tech/react.png' },
    { name: 'Next.js', image: '/images/tech/nextjs.png' },
    { name: 'Node.js', image: '/images/tech/nodejs.png' },
    { name: 'MongoDB', image: '/images/tech/mongodb.png' },
    { name: 'MySQL', image: '/images/tech/mysql.png' },
    { name: 'PostgreSQL', image: '/images/tech/postgresql.png' },
    { name: 'Python', image: '/images/tech/Python.png' },
    { name: 'Flutter', image: '/images/tech/flutter.png' },
    { name: 'Kotlin', image: '/images/tech/kotlin.png' },
    { name: 'Swift', image: '/images/tech/swift.png' },
    { name: 'Tailwind CSS', image: '/images/tech/Tailwind-CSS.png' },
    { name: 'TypeScript', image: '/images/tech/typescript.png' },
    { name: 'AWS', image: '/images/tech/AWS.png' },
    { name: 'Firebase', image: '/images/tech/Firebase.png' },
    { name: 'Redux', image: '/images/tech/Redux.png' },
    { name: 'PHP', image: '/images/tech/php.png' },
    { name: 'Laravel', image: '/images/tech/laravel.png' },
    { name: 'WordPress', image: '/images/tech/WordPress.png' },
    { name: 'Docker', image: '/images/tech/Docker.png' },
    { name: 'Figma', image: '/images/tech/Figma.png' },
];
