export const COMMON_TECH = [
    { name: 'React', image: '/images/tech/React.png' },
    { name: 'Next.js', image: '/images/tech/Next.js.png' },
    { name: 'Node.js', image: '/images/tech/nodejs.png' },
    { name: 'MongoDB', image: '/images/tech/MongoDB.png' },
    { name: 'MySQL', image: '/images/tech/MySQL.png' },
    { name: 'PostgreSQL', image: '/images/tech/postgresql.png' },
    { name: 'Python', image: '/images/tech/Python.png' },
    { name: 'Flutter', image: '/images/tech/Flutter.png' },
    { name: 'Kotlin', image: '/images/tech/Kotlin.png' },
    { name: 'Swift', image: '/images/tech/Swift.png' },
    { name: 'Tailwind CSS', image: '/images/tech/Tailwind-CSS.png' },
    { name: 'TypeScript', image: '/images/tech/TypeScript.png' },
    { name: 'AWS', image: '/images/tech/AWS.png' },
    { name: 'Firebase', image: '/images/tech/Firebase.png' },
    { name: 'Redux', image: '/images/tech/Redux.png' },
    { name: 'PHP', image: '/images/tech/PHP.png' },
    { name: 'Laravel', image: '/images/tech/Laravel.png' },
    { name: 'WordPress', image: '/images/tech/WordPress.png' },
    { name: 'Docker', image: '/images/tech/Docker.png' },
    { name: 'Figma', image: '/images/tech/Figma.png' },
];
