export const BLOG_SECTIONS = {
  insights: {
    title: "Insights",
    slugBase: "/insights",
    types: ["insight"],
    heroBg: "/images/insights/hero-insights.png",
    heroLabel: "Softkingo insights",
    heroHeading: "Explore insights & strategies",
    heroSub:
      "Deep dives into product, UX and engineering decisions behind real projects.",
    listHeading: "All insights",
    emptyText: "No insights published yet.",
    featuredCta: "Read insight →",
    newsletterList: {
      name: "Insights Newsletter",
      slug: "insights-newsletter",
      description: "Newsletter for insights, strategies and deep dives.",
    },
  },
  blog: {
    title: "Blog",
    slugBase: "/blog",
    types: ["blog"],
    heroBg: "/images/blog/hero-blog.png",
    heroLabel: "Softkingo blog",
    heroHeading: "Ideas, insights & launch playbooks",
    heroSub:
      "Product, design and engineering stories to help you plan, ship and scale better mobile and web apps.",
    listHeading: "All blog posts",
    emptyText: "No blog posts yet.",
    featuredCta: "Read article →",
    newsletterList: {
      name: "Blog Newsletter",
      slug: "blog-newsletter",
      description: "Main blog newsletter list.",
    },
  },
  featured: {
    title: "Featured",
    slugBase: "/featured",
    types: ["featured"],
    heroBg: "/images/featured/hero-featured.png",
    heroLabel: "Featured stories",
    heroHeading: "Handpicked stories & case studies",
    heroSub:
      "Curated long‑form content that goes deep into product strategy and complex builds.",
    listHeading: "Featured stories",
    emptyText: "No featured stories yet.",
    featuredCta: "Explore story →",
    newsletterList: {
      name: "Featured Newsletter",
      slug: "featured-newsletter",
      description: "Updates when we publish featured stories.",
    },
  },
  "e-guides": {
    title: "E‑Guides",
    slugBase: "/e-guides",
    types: ["e-guide"],
    heroBg: "/images/guides/hero-eguides.png",
    heroLabel: "Softkingo e‑guides",
    heroHeading: "Step‑by‑step product playbooks",
    heroSub:
      "Structured guides to plan, build and scale web and mobile products.",
    listHeading: "All e‑guides",
    emptyText: "No e‑guides available yet.",
    featuredCta: "View guide →",
    newsletterList: {
      name: "E‑Guides Newsletter",
      slug: "eguides-newsletter",
      description: "Get updates when new guides go live.",
    },
  },
  "press-releases": {
    title: "Press Releases",
    slugBase: "/press-releases",
    types: ["press-release"],
    heroBg: "/images/press/hero-press.png",
    heroLabel: "Press releases",
    heroHeading: "Company launches & milestones",
    heroSub:
      "Official announcements on partnerships, launches and company updates.",
    listHeading: "All press releases",
    emptyText: "No press releases yet.",
    featuredCta: "Read release →",
    newsletterList: {
      name: "Press Updates",
      slug: "press-newsletter",
      description: "Press releases and company announcements.",
    },
  },
  guides: {
    title: "Product Guides",
    slugBase: "/guides",
    types: ["product-guide"],
    heroBg: "/images/guides/hero-guides.png",
    heroLabel: "Product guides",
    heroHeading: "Feature breakdowns & how‑tos",
    heroSub:
      "How‑to guides for PMs, founders and engineering leads across product and tech.",
    listHeading: "All product guides",
    emptyText: "No guides yet.",
    featuredCta: "Read guide →",
    newsletterList: {
      name: "Guides Newsletter",
      slug: "guides-newsletter",
      description: "Product and feature guide updates.",
    },
  },
  "media-coverage": {
    title: "Media Coverage",
    slugBase: "/media-coverage",
    types: ["media-coverage"],
    heroBg: "/images/media/hero-media.png",
    heroLabel: "Media coverage",
    heroHeading: "What the world says about us",
    heroSub:
      "Stories and mentions from global media and industry platforms.",
    listHeading: "All media coverage",
    emptyText: "No media coverage yet.",
    featuredCta: "Read story →",
    newsletterList: {
      name: "Media Coverage Digest",
      slug: "media-coverage-newsletter",
      description: "Roundup of media mentions and features.",
    },
  },
  articles: {
    title: "Articles",
    slugBase: "/articles",
    types: ["article"],
    heroBg: "/images/articles/hero-articles.png",
    heroLabel: "Technical articles",
    heroHeading: "Deep dives into tech & architecture",
    heroSub:
      "In‑depth articles on cloud, AI, app architecture, performance and more.",
    listHeading: "All articles",
    emptyText: "No articles yet.",
    featuredCta: "Read article →",
    newsletterList: {
      name: "Technical Articles Newsletter",
      slug: "articles-newsletter",
      description: "Engineering and architecture articles.",
    },
  },
  whitepapers: {
    title: "Whitepapers",
    slugBase: "/whitepapers",
    types: ["whitepaper"],
    heroBg: "/images/whitepapers/hero-whitepapers.png",
    heroLabel: "Whitepapers",
    heroHeading: "Research‑backed tech documents",
    heroSub:
      "Research on emerging tech and enterprise adoption from the field.",
    listHeading: "All whitepapers",
    emptyText: "No whitepapers yet.",
    featuredCta: "View whitepaper →",
    newsletterList: {
      name: "Whitepapers Newsletter",
      slug: "whitepapers-newsletter",
      description: "New whitepapers and research updates.",
    },
  },
  podcasts: {
    title: "Podcasts",
    slugBase: "/podcasts",
    types: ["podcast"],
    heroBg: "/images/podcasts/hero-podcasts.png",
    heroLabel: "Podcasts",
    heroHeading: "Conversations with builders",
    heroSub:
      "Podcast episodes with product, design and engineering leaders.",
    listHeading: "All podcast episodes",
    emptyText: "No podcasts yet.",
    featuredCta: "Listen now →",
    newsletterList: {
      name: "Podcast Newsletter",
      slug: "podcasts-newsletter",
      description: "New podcast episodes and highlights.",
    },
  },
};
